"""City coverage report: cities.yaml + data/attractions → docs/CITIES.md.

The file is generated so the list of covered cities can never drift from the data.
`ingest` and `seed` rewrite it; `cities-doc --check` fails when it is stale (CI).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .config import CitiesConfig
from .paths import REPO_ROOT

CITIES_DOC = REPO_ROOT / "docs" / "CITIES.md"


def _pct(part: int, total: int) -> str:
    return f"{round(100 * part / total)}%" if total else "–"


def city_stats(doc: dict[str, Any] | None) -> dict[str, Any] | None:
    if doc is None:
        return None
    items = doc.get("attractions", [])
    n = len(items)
    return {
        "attractions": n,
        "images": _pct(sum(1 for a in items if a.get("image_url")), n),
        "names_pt": _pct(sum(1 for a in items if a.get("name_pt")), n),
        "hours": _pct(sum(1 for a in items if a.get("opening_hours")), n),
        "unesco": sum(1 for a in items if a.get("is_unesco")),
        "retrieved": doc.get("retrieved") or "–",
    }


def render(
    config: CitiesConfig,
    docs: dict[str, dict[str, Any]],
    countries: dict[str, dict[str, Any]],
) -> str:
    rows: list[str] = []
    total = 0
    active = 0
    missing: list[str] = []
    for i, city in enumerate(config.cities, start=1):
        stats = city_stats(docs.get(city.slug))
        country = countries.get(city.country_code, {}).get("name_en", city.country_code)
        status = "active" if city.is_active else "inactive"
        if stats is None:
            missing.append(city.slug)
            status = "not ingested"
            cells = ["0", "–", "–", "–", "–", "–"]
        else:
            total += stats["attractions"]
            cells = [
                f"{stats['attractions']:,}",
                stats["images"],
                stats["names_pt"],
                stats["hours"],
                str(stats["unesco"]),
                stats["retrieved"],
            ]
        if city.is_active and stats is not None:
            active += 1
        rows.append(
            f"| {i} | {city.name.en} | {city.name.pt} | {country} ({city.country_code}) "
            f"| `{city.slug}` | {' | '.join(cells)} | {status} |"
        )

    n_countries = len({c.country_code for c in config.cities})
    lines = [
        "# Covered cities",
        "",
        "<!-- Generated by `python -m wayfarer_pipeline cities-doc` from",
        "     data-pipeline/cities.yaml and data-pipeline/data/attractions. Do not edit by hand:",
        "     `ingest` and `seed` rewrite it, and CI fails when it is stale. -->",
        "",
        f"**{len(config.cities)} cities** in **{n_countries} countries**, "
        f"**{active}** live on the map, **{total:,} attractions** in total.",
        "",
        "Cities are listed in the order they were added to `cities.yaml`. When a city is added,",
        "also record it in [CHANGELOG.md](../CHANGELOG.md). How to add one: see",
        "[README → Adding a new city](../README.md#adding-a-new-city).",
        "",
        "Columns: share of attractions with an image, a Portuguese name and opening hours;",
        "number of UNESCO sites; date the data was retrieved.",
        "",
        "| # | City | PT name | Country | Slug | Attractions | Images | PT names | Hours "
        "| UNESCO | Retrieved | Status |",
        "| --: | --- | --- | --- | --- | --: | --: | --: | --: | --: | --- | --- |",
        *rows,
        "",
    ]
    if missing:
        lines += [
            f"**Not ingested yet:** {', '.join(f'`{s}`' for s in missing)} — run "
            "`python -m wayfarer_pipeline ingest --city <slug>`.",
            "",
        ]
    return "\n".join(lines)


def write(content: str, path: Path = CITIES_DOC) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


def is_current(content: str, path: Path = CITIES_DOC) -> bool:
    return path.exists() and path.read_text(encoding="utf-8") == content
