"""Generate ``supabase/seed/*.sql`` from the committed data files (no network).

Seeds are idempotent (``insert ... on conflict do update``), batched and sorted so that
re-running the pipeline produces minimal diffs.
"""

from __future__ import annotations

import uuid
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from . import attraction_texts as texts_mod
from . import city_summaries as summaries_mod
from . import countries as countries_mod
from . import visa as visa_mod
from .attractions import pipeline as attractions_mod
from .config import CitiesConfig
from .paths import SEED_DIR
from .people import pipeline as people_mod
from .sql import Raw, array, geography_point, upsert

HEADER = "-- GENERATED by data-pipeline (python -m wayfarer_pipeline {cmd}). Do not edit by hand.\n"

README_SQL = """\
-- Seed files in this folder run in filename order on `supabase db reset` and
-- `supabase db push --include-seed`. All files except this one are GENERATED by the data
-- pipeline from committed snapshots in data-pipeline/data (regenerate offline with
-- `python -m wayfarer_pipeline seed`):
--   10_countries.sql    countries (Wikidata + IANA zone.tab + curated overrides)
--   20_cities.sql       launch cities (data-pipeline/cities.yaml + Wikipedia summaries)
--   30_visa.sql         visa_requirements (passport-index-dataset, MIT)
--   40_attractions.sql  attractions (Wikidata, OpenStreetMap, Wikipedia pageviews, Commons)
--   50_people.sql       notable people of each city (Wikidata, Commons)
select 1;
"""

# Stable ids so local and hosted databases agree (the table default would be random).
ATTRACTION_NAMESPACE = uuid.NAMESPACE_URL


def attraction_uuid(qid: str) -> str:
    return str(uuid.uuid5(ATTRACTION_NAMESPACE, f"https://www.wikidata.org/entity/{qid}"))


def _write(path: Path, cmd: str, body: str) -> Path:
    path.write_text(HEADER.format(cmd=cmd) + "\n" + body, encoding="utf-8")
    return path


def countries_sql(countries: dict[str, dict[str, Any]]) -> str:
    columns = ["code", *countries_mod.FIELDS, "is_eu", "is_schengen"]
    rows = []
    for code in sorted(countries):
        c = countries[code]
        row: list[Any] = [code]
        for f in columns[1:]:
            v = c.get(f)
            if f in ("currency_codes", "plug_types", "languages", "timezones"):
                v = Raw(array(v or [], "text[]"))
            row.append(v)
        rows.append(row)
    return upsert("public.countries", columns, rows, conflict=["code"])


CITY_SUMMARY_COLUMNS = [
    "summary_en",
    "summary_pt",
    "wikipedia_en",
    "wikipedia_pt",
    "history_en",
    "history_pt",
]


def cities_sql(
    config: CitiesConfig, summaries: dict[str, summaries_mod.CitySummary] | None = None
) -> str:
    """Cities upsert; ``summaries`` (``data/city_summaries.json``) fills the About text (D-036)."""
    summaries = summaries or {}
    columns = [
        "slug",
        "name_en",
        "name_pt",
        "country_code",
        "wikidata_id",
        "center",
        "bbox",
        "timezone",
        "is_active",
        *CITY_SUMMARY_COLUMNS,
    ]
    rows = []
    for c in sorted(config.cities, key=lambda c: c.slug):
        about = summaries.get(c.slug, {})
        rows.append(
            [
                c.slug,
                c.name.en,
                c.name.pt,
                c.country_code,
                c.wikidata_id,
                geography_point(c.center[0], c.center[1]),
                Raw(array([float(v) for v in c.bbox], "double precision[]")),
                c.timezone,
                c.is_active,
                *(about.get(col) for col in CITY_SUMMARY_COLUMNS),
            ]
        )
    return upsert("public.cities", columns, rows, conflict=["slug"])


def visa_sql(rows: Iterable[dict[str, Any]]) -> str:
    columns = ["passport", "destination", "requirement", "max_stay_days", "source"]
    values = [
        [
            r["passport"],
            r["destination"],
            Raw(f"'{r['requirement']}'::public.visa_requirement"),
            r["max_stay_days"],
            visa_mod.SOURCE,
        ]
        for r in sorted(rows, key=lambda r: (r["passport"], r["destination"]))
    ]
    return upsert("public.visa_requirements", columns, values, conflict=["passport", "destination"])


# Wikipedia introduction and History excerpt (D-070), from data/attraction_texts.
TEXT_COLUMNS = ["summary_en", "summary_pt", "history_en", "history_pt"]

ATTRACTION_COLUMNS = [
    "id",
    "city_slug",
    "wikidata_id",
    "osm_id",
    "name_en",
    "name_pt",
    "description_en",
    "description_pt",
    "category",
    "location",
    "image_url",
    "image_author",
    "image_license",
    "image_license_url",
    "image_page_url",
    "is_unesco",
    "website",
    "wikipedia_en",
    "wikipedia_pt",
    "opening_hours",
    "fee",
    "avg_visit_minutes",
    "popularity",
    *TEXT_COLUMNS,
]


def _osm_id(doc: dict[str, Any], qid: str) -> str | None:
    return next((a["osm_id"] for a in doc["attractions"] if a["wikidata_id"] == qid), None)


def attractions_rows(
    docs: dict[str, dict[str, Any]],
    texts: dict[str, dict[str, texts_mod.AttractionText]] | None = None,
) -> tuple[list[list[Any]], list[str]]:
    """Rows sorted by city then wikidata id. A wikidata id is unique across the table, so an
    item that falls in two city bboxes (several Wikidata coordinates, e.g. a wrong second one)
    is kept in the city where OSM confirms it (``osm_id`` set), else the first alphabetically."""
    owner: dict[str, str] = {}
    for slug in sorted(docs):
        for a in docs[slug]["attractions"]:
            qid = a["wikidata_id"]
            if qid not in owner or (a["osm_id"] and not _osm_id(docs[owner[qid]], qid)):
                owner[qid] = slug
    warnings: list[str] = []
    rows: list[list[Any]] = []
    for slug in sorted(docs):
        items = sorted(docs[slug]["attractions"], key=lambda i: int(i["wikidata_id"][1:]))
        for a in items:
            qid = a["wikidata_id"]
            if owner[qid] != slug:
                warnings.append(f"{qid} in {slug} already seeded for {owner[qid]}; skipped")
                continue
            rows.append(
                [
                    Raw(f"'{attraction_uuid(qid)}'::uuid"),
                    slug,
                    qid,
                    a["osm_id"],
                    a["name_en"],
                    a["name_pt"],
                    a["description_en"],
                    a["description_pt"],
                    Raw(f"'{a['category']}'::public.attraction_category"),
                    geography_point(a["lat"], a["lng"]),
                    a["image_url"],
                    a["image_author"],
                    a["image_license"],
                    a["image_license_url"],
                    a["image_page_url"],
                    bool(a["is_unesco"]),
                    a["website"],
                    a["wikipedia_en"],
                    a["wikipedia_pt"],
                    a["opening_hours"],
                    a["fee"],
                    int(a["avg_visit_minutes"]),
                    int(a["popularity"]),
                    *_texts_row((texts or {}).get(slug, {}).get(qid, {})),
                ]
            )
    return rows, warnings


def _texts_row(text: texts_mod.AttractionText) -> list[str | None]:
    return [text.get(col) for col in TEXT_COLUMNS]


def attractions_sql(
    docs: dict[str, dict[str, Any]],
    texts: dict[str, dict[str, texts_mod.AttractionText]] | None = None,
) -> tuple[str, list[str]]:
    """Attractions upsert; ``texts`` (``data/attraction_texts``) fills the page texts (D-070)."""
    rows, warnings = attractions_rows(docs, texts)
    # Keep the id stable on conflict: the stored uuid is referenced by user data.
    sql = upsert("public.attractions", ATTRACTION_COLUMNS, rows, conflict=["wikidata_id"])
    sql = sql.replace("  id = excluded.id,\n", "")
    return sql, warnings


PEOPLE_COLUMNS = ["city_slug", *people_mod.FIELDS]


def _person_row(slug: str, person: dict[str, Any]) -> list[Any]:
    row: list[Any] = [slug]
    for field in people_mod.FIELDS:
        value = person.get(field)
        row.append(Raw(array(value or [], "text[]")) if field == "categories" else value)
    return row


def people_sql(docs: dict[str, dict[str, Any]]) -> str:
    """Notable people (D-071). The table holds nothing but these rows, so it is emptied first:
    a person who dropped out of a city's list must not stay."""
    rows = [
        _person_row(slug, p)
        for slug in sorted(docs)
        for p in sorted(docs[slug]["people"], key=lambda p: int(p["wikidata_id"][1:]))
    ]
    upserted = upsert(
        "public.notable_people", PEOPLE_COLUMNS, rows, conflict=["city_slug", "wikidata_id"]
    )
    return "delete from public.notable_people;\n\n" + (upserted if rows else "")


def write_readme(seed_dir: Path = SEED_DIR) -> Path:
    path = seed_dir / "00_readme.sql"
    path.write_text(README_SQL, encoding="utf-8")
    return path


def write_countries(seed_dir: Path = SEED_DIR) -> Path:
    return _write(seed_dir / "10_countries.sql", "countries", countries_sql(countries_mod.load()))


def write_cities(config: CitiesConfig, seed_dir: Path = SEED_DIR) -> Path:
    body = cities_sql(config, summaries_mod.load())
    return _write(seed_dir / "20_cities.sql", "cities", body)


def write_visa(seed_dir: Path = SEED_DIR) -> Path:
    return _write(seed_dir / "30_visa.sql", "visa", visa_sql(visa_mod.load()))


def write_people(seed_dir: Path = SEED_DIR) -> Path:
    return _write(seed_dir / "50_people.sql", "people", people_sql(people_mod.load_all()))


def write_attractions(seed_dir: Path = SEED_DIR) -> tuple[Path, list[str]]:
    sql, warnings = attractions_sql(attractions_mod.load_all(), texts_mod.load_all())
    return _write(seed_dir / "40_attractions.sql", "ingest", sql), warnings
