"""Generate ``supabase/seed/*.sql`` from the committed data files (no network).

Seeds are idempotent (``insert ... on conflict do update``), batched and sorted so that
re-running the pipeline produces minimal diffs.
"""

from __future__ import annotations

import uuid
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from . import countries as countries_mod
from . import visa as visa_mod
from .attractions import pipeline as attractions_mod
from .config import CitiesConfig
from .paths import SEED_DIR
from .sql import Raw, array, geography_point, upsert

HEADER = "-- GENERATED by data-pipeline (python -m wayfarer_pipeline {cmd}). Do not edit by hand.\n"

README_SQL = """\
-- Seed files in this folder run in filename order on `supabase db reset` and
-- `supabase db push --include-seed`. All files except this one are GENERATED by the data
-- pipeline from committed snapshots in data-pipeline/data (regenerate offline with
-- `python -m wayfarer_pipeline seed`):
--   10_countries.sql    countries (Wikidata + IANA zone.tab + curated overrides)
--   20_cities.sql       launch cities (data-pipeline/cities.yaml)
--   30_visa.sql         visa_requirements (passport-index-dataset, MIT)
--   40_attractions.sql  attractions (Wikidata, OpenStreetMap, Wikipedia pageviews, Commons)
select 1;
"""

# Stable ids so local and hosted databases agree (the table default would be random).
ATTRACTION_NAMESPACE = uuid.NAMESPACE_URL


def attraction_uuid(qid: str) -> str:
    return str(uuid.uuid5(ATTRACTION_NAMESPACE, f"https://www.wikidata.org/entity/{qid}"))


def _write(path: Path, cmd: str, body: str) -> Path:
    path.write_text(HEADER.format(cmd=cmd) + "\n" + body, encoding="utf-8")
    return path


def countries_sql(countries: dict[str, dict[str, Any]]) -> str:
    columns = ["code", *countries_mod.FIELDS, "is_eu", "is_schengen"]
    rows = []
    for code in sorted(countries):
        c = countries[code]
        row: list[Any] = [code]
        for f in columns[1:]:
            v = c.get(f)
            if f in ("currency_codes", "plug_types", "languages", "timezones"):
                v = Raw(array(v or [], "text[]"))
            row.append(v)
        rows.append(row)
    return upsert("public.countries", columns, rows, conflict=["code"])


def cities_sql(config: CitiesConfig) -> str:
    columns = [
        "slug",
        "name_en",
        "name_pt",
        "country_code",
        "wikidata_id",
        "center",
        "bbox",
        "timezone",
        "is_active",
    ]
    rows = []
    for c in sorted(config.cities, key=lambda c: c.slug):
        rows.append(
            [
                c.slug,
                c.name.en,
                c.name.pt,
                c.country_code,
                c.wikidata_id,
                geography_point(c.center[0], c.center[1]),
                Raw(array([float(v) for v in c.bbox], "double precision[]")),
                c.timezone,
                c.is_active,
            ]
        )
    return upsert("public.cities", columns, rows, conflict=["slug"])


def visa_sql(rows: Iterable[dict[str, Any]]) -> str:
    columns = ["passport", "destination", "requirement", "max_stay_days", "source"]
    values = [
        [
            r["passport"],
            r["destination"],
            Raw(f"'{r['requirement']}'::public.visa_requirement"),
            r["max_stay_days"],
            visa_mod.SOURCE,
        ]
        for r in sorted(rows, key=lambda r: (r["passport"], r["destination"]))
    ]
    return upsert("public.visa_requirements", columns, values, conflict=["passport", "destination"])


ATTRACTION_COLUMNS = [
    "id",
    "city_slug",
    "wikidata_id",
    "osm_id",
    "name_en",
    "name_pt",
    "description_en",
    "description_pt",
    "category",
    "location",
    "image_url",
    "image_author",
    "image_license",
    "image_license_url",
    "image_page_url",
    "is_unesco",
    "website",
    "wikipedia_en",
    "wikipedia_pt",
    "opening_hours",
    "fee",
    "avg_visit_minutes",
    "popularity",
]


def attractions_rows(docs: dict[str, dict[str, Any]]) -> tuple[list[list[Any]], list[str]]:
    """Rows sorted by city then wikidata id. A wikidata id is unique across the table, so an
    item that falls in two city bboxes is kept in the first city (alphabetical)."""
    seen: dict[str, str] = {}
    warnings: list[str] = []
    rows: list[list[Any]] = []
    for slug in sorted(docs):
        items = sorted(docs[slug]["attractions"], key=lambda i: int(i["wikidata_id"][1:]))
        for a in items:
            qid = a["wikidata_id"]
            if qid in seen:
                warnings.append(f"{qid} in {slug} already seeded for {seen[qid]}; skipped")
                continue
            seen[qid] = slug
            rows.append(
                [
                    Raw(f"'{attraction_uuid(qid)}'::uuid"),
                    slug,
                    qid,
                    a["osm_id"],
                    a["name_en"],
                    a["name_pt"],
                    a["description_en"],
                    a["description_pt"],
                    Raw(f"'{a['category']}'::public.attraction_category"),
                    geography_point(a["lat"], a["lng"]),
                    a["image_url"],
                    a["image_author"],
                    a["image_license"],
                    a["image_license_url"],
                    a["image_page_url"],
                    bool(a["is_unesco"]),
                    a["website"],
                    a["wikipedia_en"],
                    a["wikipedia_pt"],
                    a["opening_hours"],
                    a["fee"],
                    int(a["avg_visit_minutes"]),
                    int(a["popularity"]),
                ]
            )
    return rows, warnings


def attractions_sql(docs: dict[str, dict[str, Any]]) -> tuple[str, list[str]]:
    rows, warnings = attractions_rows(docs)
    # Keep the id stable on conflict: the stored uuid is referenced by user data.
    sql = upsert("public.attractions", ATTRACTION_COLUMNS, rows, conflict=["wikidata_id"])
    sql = sql.replace("  id = excluded.id,\n", "")
    return sql, warnings


def write_readme(seed_dir: Path = SEED_DIR) -> Path:
    path = seed_dir / "00_readme.sql"
    path.write_text(README_SQL, encoding="utf-8")
    return path


def write_countries(seed_dir: Path = SEED_DIR) -> Path:
    return _write(seed_dir / "10_countries.sql", "countries", countries_sql(countries_mod.load()))


def write_cities(config: CitiesConfig, seed_dir: Path = SEED_DIR) -> Path:
    return _write(seed_dir / "20_cities.sql", "cities", cities_sql(config))


def write_visa(seed_dir: Path = SEED_DIR) -> Path:
    return _write(seed_dir / "30_visa.sql", "visa", visa_sql(visa_mod.load()))


def write_attractions(seed_dir: Path = SEED_DIR) -> tuple[Path, list[str]]:
    sql, warnings = attractions_sql(attractions_mod.load_all())
    return _write(seed_dir / "40_attractions.sql", "ingest", sql), warnings
