-- Seed files in this folder run in filename order on `supabase db reset` and
-- `supabase db push --include-seed`. All files except this one are GENERATED by the data
-- pipeline from committed snapshots in data-pipeline/data (regenerate offline with
-- `python -m wayfarer_pipeline seed`):
--   10_countries.sql    countries (Wikidata + IANA zone.tab + curated overrides)
--   20_cities.sql       launch cities (data-pipeline/cities.yaml + Wikipedia summaries)
--   30_visa.sql         visa_requirements (passport-index-dataset, MIT)
--   40_attractions.sql  attractions (Wikidata, OpenStreetMap, Wikipedia pageviews, Commons)
--   50_people.sql       notable people of each city (Wikidata, Commons)
select 1;
