-- GENERATED by data-pipeline (python -m wayfarer_pipeline cities). Do not edit by hand.

insert into public.cities (slug, name_en, name_pt, country_code, wikidata_id, center, bbox, timezone, is_active) values
  ('amsterdam', 'Amsterdam', 'Amesterdão', 'NL', 'Q727', extensions.st_setsrid(extensions.st_makepoint(4.883333, 52.366667), 4326)::extensions.geography, array[52.2781742,4.7287776,52.4310638,5.0791622]::double precision[], 'Europe/Amsterdam', true),
  ('barcelona', 'Barcelona', 'Barcelona', 'ES', 'Q1492', extensions.st_setsrid(extensions.st_makepoint(2.176944, 41.3825), 4326)::extensions.geography, array[41.3170354,2.0524977,41.4679135,2.2283555]::double precision[], 'Europe/Madrid', true),
  ('istanbul', 'Istanbul', 'Istambul', 'TR', 'Q406', extensions.st_setsrid(extensions.st_makepoint(28.960278, 41.01), 4326)::extensions.geography, array[40.846381,28.8158715,41.166381,29.1358715]::double precision[], 'Europe/Istanbul', true),
  ('lisbon', 'Lisbon', 'Lisboa', 'PT', 'Q597', extensions.st_setsrid(extensions.st_makepoint(-9.139016, 38.708042), 4326)::extensions.geography, array[38.6913994,-9.2298356,38.7967584,-9.0863328]::double precision[], 'Europe/Lisbon', true),
  ('london', 'London', 'Londres', 'GB', 'Q84', extensions.st_setsrid(extensions.st_makepoint(-0.1275, 51.507222), 4326)::extensions.geography, array[51.2867601,-0.5103751,51.6918741,0.3340155]::double precision[], 'Europe/London', true),
  ('madrid', 'Madrid', 'Madrid', 'ES', 'Q2807', extensions.st_setsrid(extensions.st_makepoint(-3.703333, 40.416944), 4326)::extensions.geography, array[40.3119774,-3.8889539,40.6437293,-3.5183264]::double precision[], 'Europe/Madrid', true),
  ('milan', 'Milan', 'Milão', 'IT', 'Q490', extensions.st_setsrid(extensions.st_makepoint(9.19, 45.466944), 4326)::extensions.geography, array[45.3867381,9.0408867,45.5358482,9.2781103]::double precision[], 'Europe/Rome', true),
  ('paris', 'Paris', 'Paris', 'FR', 'Q90', extensions.st_setsrid(extensions.st_makepoint(2.352222, 48.856667), 4326)::extensions.geography, array[48.8155755,2.224122,48.902156,2.4697602]::double precision[], 'Europe/Paris', true),
  ('porto', 'Porto', 'Porto', 'PT', 'Q36433', extensions.st_setsrid(extensions.st_makepoint(-8.610833, 41.15), 4326)::extensions.geography, array[41.1383507,-8.691289,41.1859353,-8.5520792]::double precision[], 'Europe/Lisbon', true),
  ('prague', 'Prague', 'Praga', 'CZ', 'Q1085', extensions.st_setsrid(extensions.st_makepoint(14.421389, 50.0875), 4326)::extensions.geography, array[49.9419006,14.2244355,50.1774302,14.7067867]::double precision[], 'Europe/Prague', true),
  ('rome', 'Rome', 'Roma', 'IT', 'Q220', extensions.st_setsrid(extensions.st_makepoint(12.482778, 41.893056), 4326)::extensions.geography, array[41.6556417,12.2344416,42.1410285,12.8557603]::double precision[], 'Europe/Rome', true),
  ('vienna', 'Vienna', 'Viena', 'AT', 'Q1741', extensions.st_setsrid(extensions.st_makepoint(16.3725, 48.208333), 4326)::extensions.geography, array[48.1179069,16.181831,48.3226679,16.5775132]::double precision[], 'Europe/Vienna', true)
on conflict (slug) do update set
  name_en = excluded.name_en,
  name_pt = excluded.name_pt,
  country_code = excluded.country_code,
  wikidata_id = excluded.wikidata_id,
  center = excluded.center,
  bbox = excluded.bbox,
  timezone = excluded.timezone,
  is_active = excluded.is_active,
  updated_at = now();
